### PR TITLE
fix: build errors

### LINKED ISSUE #66: Bug: build type error
Image

### PR DESCRIPTION
**Pull request by matibox**
Fixes #66

### CODE REVIEW

File: src/app/(dashboard)/@modal/(.)calendar/[eventId]/page.tsx [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
-export default function EventDetailsModalPage({
-  params: { eventId: _eventId },
+export default async function EventDetailsModalPage({
+  params,
 }: {
-  params: { eventId: string };
+  params: Promise<{ eventId: string }>;
 }) {
-  const eventId = parseInt(_eventId);
+  const { eventId } = await params;
```
Comment (Skoczowianin) [inline src/app/(dashboard)/@modal/(.)calendar/[eventId]/page.tsx:8]: Is await necessary?

File: src/app/(dashboard)/calendar/[eventId]/page.tsx [hunk 2]
```diff
@@ -2,10 +2,11 @@ import { api } from '~/trpc/server';
 import EventDetails from './_components/EventDetails';
 
 export default async function EventDetailsPage({
-  params: { eventId: _eventId },
+  params,
 }: {
-  params: { eventId: string };
+  params: Promise<{ eventId: string }>;
 }) {
+  const { eventId: _eventId } = await params;
```
Comment (Skoczowianin) [inline src/app/(dashboard)/calendar/[eventId]/page.tsx:9]: Same, is await necessary?

Comment (Skoczowianin) [reply src/app/(dashboard)/calendar/[eventId]/page.tsx:9]: ok, clear https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#good-to-know

File: src/app/(dashboard)/@modal/(.)calendar/[eventId]/page.tsx (hunk 1 above)
Comment (Skoczowianin) [reply src/app/(dashboard)/@modal/(.)calendar/[eventId]/page.tsx:8]: ok, clear https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#good-to-know

**Review by Skoczowianin — APPROVED** [review]
